export const CANVAS_WIDTH = 768
export const CANVAS_HEIGHT = 768
export const BOARD_WIDTH = 4
export const BOARD_HEIGHT = 4
export const TILE_SPACING = 20
export const TILE_WIDTH = (CANVAS_WIDTH - (TILE_SPACING * (BOARD_WIDTH + 1))) / BOARD_WIDTH
export const TILE_HEIGHT = (CANVAS_HEIGHT - (TILE_SPACING * (BOARD_HEIGHT + 1))) / BOARD_HEIGHT